### PR TITLE
feat: add Edge API v1.1 support

### PR DESCRIPTION
**Pull request by mezannic**
Here is what I came with following Edge API v1.1 documentation.
It shouldn't introduce any breaking change apart from the conversion of `EdgeApiOptions` from a TypeScript _interface_ to a TypeScript _type_ (do we need a major for that?).

I don't have a v1.0 API client secret / access token URL pair, so I can't test if the addition of `X-Client-ID` header to v1.0 API requests has an impact on the response status code.
I didn't test v1.1 API requests either as I don't have any change to submit to my extension yet.

### CODE REVIEW

**Comment by mezannic** [comment]
@aklinker1 You were quick to review!
Good job spotting the CLI options I forgot to add.
Your changes broke some test, I fixed it in a following commit.

**Review by aklinker1 — APPROVED** [review]
OK, code looks good. I'll run the E2E tests, and if they pass, we'll get this merged and released.

**Comment by aklinker1** [comment]
Yeah, still getting 401s whatever I try. Sent an email to microsoft asking for help.

**Comment by aklinker1** [comment]
Problem was the `X-Client-ID` header - it should have been `X-ClientID` without the second dash.

**Comment by aklinker1** [comment]
Released in [`v2.3.0`](https://github.com/aklinker1/publish-browser-extension/releases/tag/v2.3.0)

**Comment by mezannic** [comment]
Thank you for the update!
And sorry for wasting your time with this typo… ^^'

**Pull request merged**
